/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author DIEGO_LOPEZ
 */
public class IntefazBase extends javax.swing.JFrame {

    /**
     * Creates new form IntefazBase
     */
    public IntefazBase() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Salir1 = new javax.swing.JButton();
        Estadisticas = new javax.swing.JButton();
        Empresa1 = new javax.swing.JButton();
        Empresa2 = new javax.swing.JButton();
        Empresa3 = new javax.swing.JButton();
        fondobase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Bienvenido al congreso de empresas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        Salir1.setBackground(new java.awt.Color(255, 0, 0));
        Salir1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir1.setForeground(new java.awt.Color(255, 255, 255));
        Salir1.setText("X");
        Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir1ActionPerformed(evt);
            }
        });
        getContentPane().add(Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        Estadisticas.setText("Estadisticas");
        getContentPane().add(Estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 150, -1));

        Empresa1.setText("Empresa 1");
        getContentPane().add(Empresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, 40));

        Empresa2.setText("Empresa 2");
        Empresa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Empresa2ActionPerformed(evt);
            }
        });
        getContentPane().add(Empresa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 150, 40));

        Empresa3.setText("Empresa 3");
        getContentPane().add(Empresa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 150, 40));

        fondobase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/02d7b2072c41a1cd5b4237c49ce2754c.jpg"))); // NOI18N
        getContentPane().add(fondobase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Empresa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Empresa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Empresa2ActionPerformed

    private void Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntefazBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntefazBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntefazBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntefazBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntefazBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Empresa1;
    private javax.swing.JButton Empresa2;
    private javax.swing.JButton Empresa3;
    private javax.swing.JButton Estadisticas;
    private javax.swing.JButton Salir1;
    private javax.swing.JLabel fondobase;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
